name: conditional workflow

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  conditional-workflow:
    uses: Bishal05das/github-actions-practice/.github/workflows/11-reuseable-workflow.yml
