name: conditional workflow

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
     - name: build backend image
       run: |
        echo "building backend image"