name: predefined workflow

on: 
  workflow_dispatch:

jobs:
  predefined-workflow:
    runs-on: ubuntu-latest

    steps:
     - name: Nodejs version
       run: node -v

     - name: setup nodejs
       uses: actions/setup-node@v4
       with:
        node-version: '24'

     - name: Nodejs version
       run: node -v
